### ISSUE TITLE
TypeError: CurseForgeAPI.getMinecraftModloaders() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by igorir3** [James2854/CurseforgeAPy#2] opened 2022-12-27 20:09 UTC
Traceback (most recent call last):
  File "C:\Users\kiril\Desktop\MLP\main.py", line 17, in <module>
    minecraftModloaders = cf.getMinecraftModloaders()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CurseForgeAPI.getMinecraftModloaders() missing 1 required positional argument: 'self'

**Comment by igorir3** [comment] 2022-12-27 20:11
Oh, no.. Everything need 'self' '-_-

**Comment by igorir3** [comment] 2022-12-27 20:15
I looked into the code and the problem is most likely in the enum library. Which I can't download -_-... Gives AttributeError error: module 'enum' has no attribute 'global_enum'

**Comment by Eriall1** [comment] 2022-12-28 19:18
Hi,
enum is a builtin library in python since 3.4, it should be included within your python distribution if you are using a version above or equal to 3.4.

I will have a look into the other issue, thanks for reporting it.

**Comment by igorir3** [comment] 2022-12-28 19:21
> Hi,
> enum is a builtin library in python since 3.4, it should be included within your python distribution if you are using a version above or equal to 3.4.
> 
> I will have a look into the other issue, thanks for reporting it.

I'm used (and using) python 3.11

**Comment by Eriall1** [comment] 2022-12-28 19:32
Hi there,

If possible, would you be able to post the code to reproduce this error?
I am having trouble recreating it, as everything seems to work as usual.

**Comment by Eriall1** [comment] 2022-12-28 19:33
> > Hi,
> > enum is a builtin library in python since 3.4, it should be included within your python distribution if you are using a version above or equal to 3.4.
> > I will have a look into the other issue, thanks for reporting it.
> 
> I'm used (and using) python 3.11

Using the following code:
```
from CurseForgeAPy import CurseForgeAPI

cf = CurseForgeAPI("my-api-key")

# Get the modloaders
minecraftModloaders = cf.getMinecraftModloaders()
print(minecraftModloaders)
```
Everything seems to work fine

**Comment by igorir3** [comment] 2022-12-28 19:56
That's the problem! That's what I did!

**Comment by igorir3** [comment] 2022-12-28 19:56
Word for word

**Comment by igorir3** [comment] 2022-12-28 19:57
And one more thing: I will stop answering for now since it's already 11 pm in my country

**Comment by Eriall1** [comment] 2022-12-28 21:02
Very odd. Despite what the documentation says, the minecraft modloader endpoint you are trying to access doesnt actually require authentication, so its not to do with that. I have no idea what would cause it to fail on your machine, try upgrading the package using `pip3 install --upgrade curseforgeapy`.

The package seems to work fine on the several versions of python I have tested it on as well as Windows 10 and Ubuntu 18.04. If upgrading the package doesnt help, I'm not sure what will, assuming you have copy pasted the sample code. Apologies for not being able to help more.

**Comment by igorir3** [comment] 2022-12-30 16:38
ModuleNotFoundError: No module named 'CurseForgeAPy.schemaClasses'

**Comment by Eriall1** [comment] 2023-01-01 15:32
> ModuleNotFoundError: No module named 'CurseForgeAPy.schemaClasses'

Again, if you upgrade to the latest version this shouldnt happen. Initially it was caused by an update that i did mark as breaking, then later reverted.

**Comment by igorir3** [comment] 2023-01-02 17:18
Alleluia! It works

**Comment by igorir3** [comment] 2023-01-02 17:30
However, a question arose! And how to download and then run minecraft with the forge core?

**Comment by Eriall1** [comment] 2023-01-03 06:18
> However, a question arose! And how to download and then run minecraft with the forge core?

personally, I use PolyMC [which can be found here](https://polymc.org/download/). It lets you have multiple instances with different mods. Otherwise, just follow the guide [here](https://www.pcgamer.com/how-to-use-minecraft-forge-download-install/)

I will now be closing the issue, since this is technically out of scope for the package

**Closed as completed by Eriall1** 2023-01-03 06:18 UTC

**Comment by igorir3** [comment] 2023-01-03 09:41
Thanks :)

**Comment by igorir3** [comment] 2023-01-03 09:43
But, you didn't understand my question a little, I meant installation, and then launch via python or via the sys module

**Comment by igorir3** [comment] 2023-01-03 09:50
Although I kind of found a library for that.... If necessary, I can unsubscribe what kind of library and throw off an example of work

**Comment by Eriall1** [comment] 2023-01-03 09:51
Oh, I have no idea.

How I'd do it is probably upload a github repo with all the necessary files, then download it within the script and place them in the relevant places (.minecraft etc). 

Then you can use the os.system to run a shell command to launch it.

Probably give it a google, but thats the general gist of how I would implement it.

**Comment by Eriall1** [comment] 2023-01-03 09:53
continue the discussion in https://github.com/James2854/CurseForgeAPy/discussions/4#discussion-4716753
 if you would like.
