### ISSUE TITLE
CurseForgeAPI.searchMods() missing 1 required positional

### ISSUE THREAD

**Issue by igorir3** [James2854/CurseforgeAPy#1] opened 2022-12-27 20:07 UTC
Traceback (most recent call last):
  File "C:\Users\kiril\Desktop\MLP\main.py", line 17, in <module>
    searchResults = CurseForgeAPI.searchMods(432)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CurseForgeAPI.searchMods() missing 1 required positional argument: 'gameId'

**Comment by igorir3** [comment] 2022-12-27 20:15
I looked into the code and the problem is most likely in the enum library. Which I can't download -_-... Gives AttributeError error: module 'enum' has no attribute 'global_enum'

**Comment by Eriall1** [comment] 2022-12-28 19:30
Hi,
I looked into this issue.

Unlike the misleading error message, the issue is most likely to do with the client not being instantiated. In order to use many of the methods within the CurseForgeAPI object, you will need to first initialise it into an actual object, rather then call the methods directly. Currently, the method thinks you are passing `432` into the method as the self parameter, rather then the gameId.

Instantiating the api can be done through this code:
`cf = CurseForgeAPI("my-api-code")`
which will allow you to use the searchMods method.

I will close the issue, though am interested in why you believe the problem is the enum module. Feel free to reopen if you have any other problems.

**Closed as completed** 2022-12-28 19:30 UTC
